### ISSUE TITLE
Coredump: checkpoint_###.tmp-###/parameter does not exist when pretraining from scratch

### ISSUE THREAD

**Issue by boram915** [google-research/t5x#1091]
Hi
I am repeatedly facing the error that a parameter of random checkpoint does not exist.
This happens whenever I pretrained the model from scratch.
Whenever I run the code, the iterations (epochs) that the error occurs were different. 
I uses custom dataset with span corruption task on v3-32 pod instance.
The full error message is below.
I tried to figure out why this happens, but could not get any information. Also I deleted and create new v3-32 pod instance.
Also, I want to ask if it is write to run the code by the below line?
`gcloud alpha compute tpus tpu-vm ssh [tpu-name] --worker all --command "python train.py" `
Because XManager codebases assumes Python 3.9+ but tpu-vm-base has python 3.8, I haven't tried it yet.
Any comments or hints are very appreciated.

```
Removing gs://[bucket-name]/model/pretraining/small/230213-0619/checkpoint_966000.tmp-1676360415/target.encoder.layers_2.attention.out.kernel/0.0...
Removing gs://[bucket-name]/model/pretraining/small/230213-0619/checkpoint_966000.tmp-1676360415/target.encoder.layers_7.mlp.wi_0.kernel/0.0...
INFO 0214 07:41:08.878841 retry_util.py] Retrying request, attempt #1...
NotFoundException: 404 gs://[bucket-name]/model/pretraining/small/230213-0619/checkpoint_966000.tmp-1676360415/target.decoder.layers_2.mlp.wi_0.kernel/0.0 does not exist.
CommandException: 1 file/object could not be transferred.
Traceback (most recent call last):MiB]  99% Done
  File "/home/[username]/t5x/t5x/train.py", line 810, in <module>
    gin_utils.run(main)
  File "/home/[username]/t5x/t5x/gin_utils.py", line 130, in run
    app.run(
  File "/home/[username]/.local/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/[username]/.local/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/[username]/t5x/t5x/train.py", line 771, in main
    _main(argv)
  File "/home/[username]/t5x/t5x/train.py", line 806, in _main
    train_using_gin()
  File "/home/[username]/.local/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/[username]/.local/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/[username]/.local/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/[username]/t5x/t5x/train.py", line 681, in train
    checkpoint_manager.save(trainer.train_state,
  File "/home/[username]/t5x/t5x/utils.py", line 450, in save
    self._checkpointer.save(
  File "/home/[username]/t5x/t5x/utils.py", line 256, in save
    self._save_checkpointer.save(
  File "/home/[username]/t5x/t5x/checkpoints.py", line 816, in save
    subprocess.run(['gsutil', '-m', 'mv', tmp_dir, final_dir],
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gsutil', '-m', 'mv', 'gs://[bucket-name]/model/pretraining/small/230213-0619/checkpoint_966000.tmp-1676360415', 'gs://[bucket-name]/model/pretraining/small/230213-0619/checkpoint_966000']' returned non-zero exit status 1.
  In call to configurable 'train' (<function train at 0x7fca2738d040>)

==> NOTE: You are uploading one or more large file(s), which would run
significantly faster if you enable parallel composite uploads. This
feature can be enabled by editing the
"parallel_composite_upload_threshold" value in your .boto
configuration file. However, note that if you do this large files will
be uploaded as `composite objects
<https://cloud.google.com/storage/docs/composite-objects>`_,which
means that any user who downloads such objects will need to have a
compiled crcmod installed (see "gsutil help crcmod"). This is because
without a compiled crcmod, computing checksums on composite objects is
so slow that gsutil disables downloads of composite objects.

/ [1 files][222.7 MiB/222.7 MiB]
Operation completed over 1 objects/222.7 MiB.
E0214 07:43:48.656198   14278 coredump_hook.cc:414] RAW: Remote crash data gathering hook invoked.
E0214 07:43:48.656220   14278 coredump_hook.cc:453] RAW: Called via ReportEvent and disabled coredump
E0214 07:43:48.656239   14278 client.cc:278] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0214 07:43:48.656245   14278 coredump_hook.cc:512] RAW: Sending fingerprint to remote end.
E0214 07:43:48.656250   14278 coredump_socket.cc:120] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0214 07:43:48.656254   14278 coredump_hook.cc:518] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0214 07:43:48.656257   14278 coredump_hook.cc:580] RAW: Dumping core locally.
```

**Comment by boram915** [comment]
[Additional report] Same issues were observed when finetune. When this happens, train.py stopped in one random worker of 4 VM of v3-32.
