### ISSUE TITLE
Cannot open files in t5x/notebooks

### ISSUE THREAD

**Issue by Lena810** [google-research/t5x#1094]
I cannot open files in t5x/notebooks/ and the error message is:
Unexpected token ']', ..."n",
      ]
    },
 "... is not valid JSON
SyntaxError: Unexpected token ']', ..."n",
      ]
    },
 "... is not valid JSON
    at JSON.parse (<anonymous>)
    at xa.program_ (https://ssl.gstatic.com/colaboratory-static/common/9046a146e1ae7f705b9d75ac3cf9a2a2/external_polymer_binary_l10n__zh_cn.js:6384:302)
    at za (https://ssl.gstatic.com/colaboratory-static/common/9046a146e1ae7f705b9d75ac3cf9a2a2/external_polymer_binary_l10n__zh_cn.js:21:57)
    at xa.next_ (https://ssl.gstatic.com/colaboratory-static/common/9046a146e1ae7f705b9d75ac3cf9a2a2/external_polymer_binary_l10n__zh_cn.js:19:195)
    at Ba.next (https://ssl.gstatic.com/colaboratory-static/common/9046a146e1ae7f705b9d75ac3cf9a2a2/external_polymer_binary_l10n__zh_cn.js:22:47)
    at b (https://ssl.gstatic.com/colaboratory-static/common/9046a146e1ae7f705b9d75ac3cf9a2a2/external_polymer_binary_l10n__zh_cn.js:22:307)

How to figure it out? Thanks.

**Comment by jhanvizala230** [comment]
Facing the same issue

**Comment by xavigonzalvo** [comment]
Try this: https://github.com/google-research/t5x/pulls/xavigonzalvo

**Comment by Lena810** [comment]
> Try this: https://github.com/google-research/t5x/pulls/xavigonzalvo

Still cannot open it.
