### ISSUE TITLE
OOM with microbatching

### ISSUE THREAD

**Issue by KeremTurgutlu** [google-research/t5x#1253]
I am able to train a umt5 small model with a batch size 128 on a single v3-8 tpu. However, when I try to enable gradient accumulation by setting batch_size=128 and num_microbatches=8 (also tried 16 but same error ocurred) OOM occurs.

Here is the gin config populated during training from `train.py`:

```
I0427 08:09:34.802999 139920159610688 gin_utils.py:85] Gin Configuration:
I0427 08:09:34.809959 139920159610688 gin_utils.py:87] from __gin__ import dynamic_registration
I0427 08:09:34.810042 139920159610688 gin_utils.py:87] import __main__ as train_script
I0427 08:09:34.810081 139920159610688 gin_utils.py:87] import seqio
I0427 08:09:34.810118 139920159610688 gin_utils.py:87] from t5x import adafactor
I0427 08:09:34.810152 139920159610688 gin_utils.py:87] from t5x.examples.scalable_t5 import network
I0427 08:09:34.810185 139920159610688 gin_utils.py:87] from t5x import gin_utils
I0427 08:09:34.810218 139920159610688 gin_utils.py:87] from t5x import models
I0427 08:09:34.810249 139920159610688 gin_utils.py:87] from t5x import partitioning
I0427 08:09:34.810280 139920159610688 gin_utils.py:87] from t5x import trainer
I0427 08:09:34.810312 139920159610688 gin_utils.py:87] from t5x import utils
I0427 08:09:34.810343 139920159610688 gin_utils.py:87] import tasks
I0427 08:09:34.810374 139920159610688 gin_utils.py:87] 
I0427 08:09:34.810405 139920159610688 gin_utils.py:87] # Macros:
I0427 08:09:34.810436 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.810466 139920159610688 gin_utils.py:87] BATCH_SIZE = 1024
I0427 08:09:34.810497 139920159610688 gin_utils.py:87] DROPOUT_RATE = 0.0
I0427 08:09:34.810528 139920159610688 gin_utils.py:87] LABEL_SMOOTHING = 0.0
I0427 08:09:34.810558 139920159610688 gin_utils.py:87] LEARNING_RATE = 0.001
I0427 08:09:34.810589 139920159610688 gin_utils.py:87] LOSS_NORMALIZING_FACTOR = None
I0427 08:09:34.810620 139920159610688 gin_utils.py:87] MIXTURE_OR_TASK_MODULE = None
I0427 08:09:34.810650 139920159610688 gin_utils.py:87] MIXTURE_OR_TASK_NAME = 'my_mixture'
I0427 08:09:34.810681 139920159610688 gin_utils.py:87] MODEL = @models.EncoderDecoderModel()
I0427 08:09:34.810712 139920159610688 gin_utils.py:87] MODEL_DIR = 'gs://...'
I0427 08:09:34.810743 139920159610688 gin_utils.py:87] OPTIMIZER = @adafactor.Adafactor()
I0427 08:09:34.810773 139920159610688 gin_utils.py:87] RANDOM_SEED = None
I0427 08:09:34.810804 139920159610688 gin_utils.py:87] SHUFFLE_TRAIN_EXAMPLES = True
I0427 08:09:34.810834 139920159610688 gin_utils.py:87] TASK_FEATURE_LENGTHS = {'inputs': 512, 'targets': 512}
I0427 08:09:34.810865 139920159610688 gin_utils.py:87] TRAIN_EVAL_MIXTURE_OR_TASK_NAME = 'my_mixture'
I0427 08:09:34.810901 139920159610688 gin_utils.py:87] TRAIN_STEPS = 1016000
I0427 08:09:34.810932 139920159610688 gin_utils.py:87] USE_CACHED_TASKS = False
I0427 08:09:34.810962 139920159610688 gin_utils.py:87] USE_CACHED_TASKS_TRAIN_EVAL = False
I0427 08:09:34.810993 139920159610688 gin_utils.py:87] USE_HARDWARE_RNG = False
I0427 08:09:34.811023 139920159610688 gin_utils.py:87] VOCAB_SIZE = 256384
I0427 08:09:34.811054 139920159610688 gin_utils.py:87] VOCABULARY = @seqio.SentencePieceVocabulary()
I0427 08:09:34.811084 139920159610688 gin_utils.py:87] Z_LOSS = 0.0001
I0427 08:09:34.811129 139920159610688 gin_utils.py:87] 
I0427 08:09:34.811161 139920159610688 gin_utils.py:87] # Parameters for adafactor.Adafactor:
I0427 08:09:34.811191 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.811222 139920159610688 gin_utils.py:87] adafactor.Adafactor.decay_rate = 0.8
I0427 08:09:34.811253 139920159610688 gin_utils.py:87] adafactor.Adafactor.logical_factor_rules = \
I0427 08:09:34.811283 139920159610688 gin_utils.py:87]     @adafactor.standard_logical_factor_rules()
I0427 08:09:34.811314 139920159610688 gin_utils.py:87] adafactor.Adafactor.step_offset = 0
I0427 08:09:34.811345 139920159610688 gin_utils.py:87] 
I0427 08:09:34.811375 139920159610688 gin_utils.py:87] # Parameters for utils.CheckpointConfig:
I0427 08:09:34.811406 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.811437 139920159610688 gin_utils.py:87] utils.CheckpointConfig.restore = @utils.RestoreCheckpointConfig()
I0427 08:09:34.811468 139920159610688 gin_utils.py:87] utils.CheckpointConfig.save = @utils.SaveCheckpointConfig()
I0427 08:09:34.811501 139920159610688 gin_utils.py:87] 
I0427 08:09:34.811527 139920159610688 gin_utils.py:87] # Parameters for utils.create_learning_rate_scheduler:
I0427 08:09:34.811554 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.811584 139920159610688 gin_utils.py:87] utils.create_learning_rate_scheduler.base_learning_rate = %LEARNING_RATE
I0427 08:09:34.811614 139920159610688 gin_utils.py:87] utils.create_learning_rate_scheduler.factors = 'rsqrt_decay'
I0427 08:09:34.811645 139920159610688 gin_utils.py:87] utils.create_learning_rate_scheduler.warmup_steps = 10000
I0427 08:09:34.811675 139920159610688 gin_utils.py:87] 
I0427 08:09:34.811706 139920159610688 gin_utils.py:87] # Parameters for utils.DatasetConfig:
I0427 08:09:34.811737 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.811767 139920159610688 gin_utils.py:87] utils.DatasetConfig.seed = 42
I0427 08:09:34.811798 139920159610688 gin_utils.py:87] 
I0427 08:09:34.811827 139920159610688 gin_utils.py:87] # Parameters for train/utils.DatasetConfig:
I0427 08:09:34.811858 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.811891 139920159610688 gin_utils.py:87] train/utils.DatasetConfig.batch_size = %BATCH_SIZE
I0427 08:09:34.811923 139920159610688 gin_utils.py:87] train/utils.DatasetConfig.mixture_or_task_name = %MIXTURE_OR_TASK_NAME
I0427 08:09:34.811954 139920159610688 gin_utils.py:87] train/utils.DatasetConfig.module = %MIXTURE_OR_TASK_MODULE
I0427 08:09:34.811983 139920159610688 gin_utils.py:87] train/utils.DatasetConfig.pack = False
I0427 08:09:34.812014 139920159610688 gin_utils.py:87] train/utils.DatasetConfig.seed = 42
I0427 08:09:34.812044 139920159610688 gin_utils.py:87] train/utils.DatasetConfig.shuffle = %SHUFFLE_TRAIN_EXAMPLES
I0427 08:09:34.812074 139920159610688 gin_utils.py:87] train/utils.DatasetConfig.split = 'train'
I0427 08:09:34.812105 139920159610688 gin_utils.py:87] train/utils.DatasetConfig.task_feature_lengths = %TASK_FEATURE_LENGTHS
I0427 08:09:34.812155 139920159610688 gin_utils.py:87] train/utils.DatasetConfig.use_cached = True
I0427 08:09:34.812187 139920159610688 gin_utils.py:87] 
I0427 08:09:34.812220 139920159610688 gin_utils.py:87] # Parameters for train_eval/utils.DatasetConfig:
I0427 08:09:34.812252 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.812284 139920159610688 gin_utils.py:87] train_eval/utils.DatasetConfig.batch_size = %BATCH_SIZE
I0427 08:09:34.812317 139920159610688 gin_utils.py:87] train_eval/utils.DatasetConfig.mixture_or_task_name = \
I0427 08:09:34.812350 139920159610688 gin_utils.py:87]     %TRAIN_EVAL_MIXTURE_OR_TASK_NAME
I0427 08:09:34.812383 139920159610688 gin_utils.py:87] train_eval/utils.DatasetConfig.module = %MIXTURE_OR_TASK_MODULE
I0427 08:09:34.812416 139920159610688 gin_utils.py:87] train_eval/utils.DatasetConfig.pack = False
I0427 08:09:34.812448 139920159610688 gin_utils.py:87] train_eval/utils.DatasetConfig.seed = 42
I0427 08:09:34.812480 139920159610688 gin_utils.py:87] train_eval/utils.DatasetConfig.shuffle = False
I0427 08:09:34.812511 139920159610688 gin_utils.py:87] train_eval/utils.DatasetConfig.split = 'validation'
I0427 08:09:34.812543 139920159610688 gin_utils.py:87] train_eval/utils.DatasetConfig.task_feature_lengths = %TASK_FEATURE_LENGTHS
I0427 08:09:34.812574 139920159610688 gin_utils.py:87] train_eval/utils.DatasetConfig.use_cached = %USE_CACHED_TASKS_TRAIN_EVAL
I0427 08:09:34.812606 139920159610688 gin_utils.py:87] 
I0427 08:09:34.812638 139920159610688 gin_utils.py:87] # Parameters for models.EncoderDecoderModel:
I0427 08:09:34.812669 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.812710 139920159610688 gin_utils.py:87] models.EncoderDecoderModel.input_vocabulary = %VOCABULARY
I0427 08:09:34.812740 139920159610688 gin_utils.py:87] models.EncoderDecoderModel.label_smoothing = %LABEL_SMOOTHING
I0427 08:09:34.812770 139920159610688 gin_utils.py:87] models.EncoderDecoderModel.loss_normalizing_factor = %LOSS_NORMALIZING_FACTOR
I0427 08:09:34.812800 139920159610688 gin_utils.py:87] models.EncoderDecoderModel.module = @network.Transformer()
I0427 08:09:34.812830 139920159610688 gin_utils.py:87] models.EncoderDecoderModel.optimizer_def = %OPTIMIZER
I0427 08:09:34.812878 139920159610688 gin_utils.py:87] models.EncoderDecoderModel.output_vocabulary = %VOCABULARY
I0427 08:09:34.812914 139920159610688 gin_utils.py:87] models.EncoderDecoderModel.z_loss = %Z_LOSS
I0427 08:09:34.812947 139920159610688 gin_utils.py:87] 
I0427 08:09:34.812979 139920159610688 gin_utils.py:87] # Parameters for utils.get_training_eval_datasets:
I0427 08:09:34.813011 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.813044 139920159610688 gin_utils.py:87] utils.get_training_eval_datasets.deterministic = False
I0427 08:09:34.813076 139920159610688 gin_utils.py:87] 
I0427 08:09:34.813108 139920159610688 gin_utils.py:87] # Parameters for partitioning.PjitPartitioner:
I0427 08:09:34.813140 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.813172 139920159610688 gin_utils.py:87] partitioning.PjitPartitioner.logical_axis_rules = \
I0427 08:09:34.813204 139920159610688 gin_utils.py:87]     @partitioning.standard_logical_axis_rules()
I0427 08:09:34.813240 139920159610688 gin_utils.py:87] partitioning.PjitPartitioner.model_parallel_submesh = (1, 1, 1, 1)
I0427 08:09:34.813291 139920159610688 gin_utils.py:87] partitioning.PjitPartitioner.num_partitions = 1
I0427 08:09:34.813327 139920159610688 gin_utils.py:87] 
I0427 08:09:34.813364 139920159610688 gin_utils.py:87] # Parameters for utils.RestoreCheckpointConfig:
I0427 08:09:34.813399 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.813435 139920159610688 gin_utils.py:87] utils.RestoreCheckpointConfig.assignment_map = None
I0427 08:09:34.813471 139920159610688 gin_utils.py:87] utils.RestoreCheckpointConfig.dtype = None
I0427 08:09:34.813507 139920159610688 gin_utils.py:87] utils.RestoreCheckpointConfig.mode = 'specific'
I0427 08:09:34.813543 139920159610688 gin_utils.py:87] utils.RestoreCheckpointConfig.path = \
I0427 08:09:34.813578 139920159610688 gin_utils.py:87]     'gs://t5-data/pretrained_models/t5x/umt5_small/checkpoint_1000000'
I0427 08:09:34.813614 139920159610688 gin_utils.py:87] utils.RestoreCheckpointConfig.strict = True
I0427 08:09:34.813649 139920159610688 gin_utils.py:87] 
I0427 08:09:34.813685 139920159610688 gin_utils.py:87] # Parameters for utils.SaveCheckpointConfig:
I0427 08:09:34.813721 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.813756 139920159610688 gin_utils.py:87] utils.SaveCheckpointConfig.dtype = 'float32'
I0427 08:09:34.813791 139920159610688 gin_utils.py:87] utils.SaveCheckpointConfig.keep = None
I0427 08:09:34.813827 139920159610688 gin_utils.py:87] utils.SaveCheckpointConfig.period = 2000
I0427 08:09:34.813862 139920159610688 gin_utils.py:87] utils.SaveCheckpointConfig.save_dataset = True
I0427 08:09:34.813901 139920159610688 gin_utils.py:87] 
I0427 08:09:34.813937 139920159610688 gin_utils.py:87] # Parameters for seqio.SentencePieceVocabulary:
I0427 08:09:34.813972 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.814008 139920159610688 gin_utils.py:87] seqio.SentencePieceVocabulary.extra_ids = 300
I0427 08:09:34.814043 139920159610688 gin_utils.py:87] seqio.SentencePieceVocabulary.sentencepiece_model_file = \
I0427 08:09:34.814079 139920159610688 gin_utils.py:87]     'gs://t5-data/vocabs/umt5.256000/sentencepiece.model'
I0427 08:09:34.814115 139920159610688 gin_utils.py:87] 
I0427 08:09:34.814150 139920159610688 gin_utils.py:87] # Parameters for network.T5Config:
I0427 08:09:34.814186 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.814223 139920159610688 gin_utils.py:87] network.T5Config.dropout_rate = %DROPOUT_RATE
I0427 08:09:34.814259 139920159610688 gin_utils.py:87] network.T5Config.dtype = 'bfloat16'
I0427 08:09:34.814295 139920159610688 gin_utils.py:87] network.T5Config.emb_dim = 512
I0427 08:09:34.814330 139920159610688 gin_utils.py:87] network.T5Config.head_dim = 64
I0427 08:09:34.814366 139920159610688 gin_utils.py:87] network.T5Config.logits_via_embedding = False
I0427 08:09:34.814402 139920159610688 gin_utils.py:87] network.T5Config.mlp_activations = ('gelu', 'linear')
I0427 08:09:34.814437 139920159610688 gin_utils.py:87] network.T5Config.mlp_dim = 1024
I0427 08:09:34.814472 139920159610688 gin_utils.py:87] network.T5Config.num_decoder_layers = 8
I0427 08:09:34.814507 139920159610688 gin_utils.py:87] network.T5Config.num_encoder_layers = 8
I0427 08:09:34.814543 139920159610688 gin_utils.py:87] network.T5Config.num_heads = 6
I0427 08:09:34.814578 139920159610688 gin_utils.py:87] network.T5Config.remat_policy = 'minimal'
I0427 08:09:34.814614 139920159610688 gin_utils.py:87] network.T5Config.scan_layers = True
I0427 08:09:34.814649 139920159610688 gin_utils.py:87] network.T5Config.vocab_size = %VOCAB_SIZE
I0427 08:09:34.814684 139920159610688 gin_utils.py:87] 
I0427 08:09:34.814719 139920159610688 gin_utils.py:87] # Parameters for train_script.train:
I0427 08:09:34.814755 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.814791 139920159610688 gin_utils.py:87] train_script.train.checkpoint_cfg = @utils.CheckpointConfig()
I0427 08:09:34.814826 139920159610688 gin_utils.py:87] train_script.train.eval_period = 2000
I0427 08:09:34.814861 139920159610688 gin_utils.py:87] train_script.train.eval_steps = 20
I0427 08:09:34.814900 139920159610688 gin_utils.py:87] train_script.train.infer_eval_dataset_cfg = None
I0427 08:09:34.814936 139920159610688 gin_utils.py:87] train_script.train.model = %MODEL
I0427 08:09:34.814971 139920159610688 gin_utils.py:87] train_script.train.model_dir = %MODEL_DIR
I0427 08:09:34.815006 139920159610688 gin_utils.py:87] train_script.train.partitioner = @partitioning.PjitPartitioner()
I0427 08:09:34.815042 139920159610688 gin_utils.py:87] train_script.train.random_seed = %RANDOM_SEED
I0427 08:09:34.815078 139920159610688 gin_utils.py:87] train_script.train.run_eval_before_training = True
I0427 08:09:34.815125 139920159610688 gin_utils.py:87] train_script.train.stats_period = 500
I0427 08:09:34.815162 139920159610688 gin_utils.py:87] train_script.train.summarize_config_fn = @gin_utils.summarize_gin_config
I0427 08:09:34.815197 139920159610688 gin_utils.py:87] train_script.train.total_steps = %TRAIN_STEPS
I0427 08:09:34.815233 139920159610688 gin_utils.py:87] train_script.train.train_dataset_cfg = @train/utils.DatasetConfig()
I0427 08:09:34.815269 139920159610688 gin_utils.py:87] train_script.train.train_eval_dataset_cfg = @train_eval/utils.DatasetConfig()
I0427 08:09:34.815304 139920159610688 gin_utils.py:87] train_script.train.train_eval_get_dataset_fn = @utils.get_training_eval_datasets
I0427 08:09:34.815340 139920159610688 gin_utils.py:87] train_script.train.trainer_cls = @trainer.Trainer
I0427 08:09:34.815376 139920159610688 gin_utils.py:87] train_script.train.use_hardware_rng = %USE_HARDWARE_RNG
I0427 08:09:34.815427 139920159610688 gin_utils.py:87] 
I0427 08:09:34.815469 139920159610688 gin_utils.py:87] # Parameters for trainer.Trainer:
I0427 08:09:34.815499 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.815529 139920159610688 gin_utils.py:87] trainer.Trainer.learning_rate_fn = @utils.create_learning_rate_scheduler()
I0427 08:09:34.815559 139920159610688 gin_utils.py:87] trainer.Trainer.num_microbatches = 16
I0427 08:09:34.815589 139920159610688 gin_utils.py:87] 
I0427 08:09:34.815619 139920159610688 gin_utils.py:87] # Parameters for network.Transformer:
I0427 08:09:34.815649 139920159610688 gin_utils.py:87] # ==============================================================================
I0427 08:09:34.815680 139920159610688 gin_utils.py:87] network.Transformer.config = @network.T5Config()
```

Error traceback:

```
Traceback (most recent call last):
  File "/home/keremturgutlu/t5x/t5x/train.py", line 844, in <module>
    gin_utils.run(main)
  File "/home/keremturgutlu/t5x/t5x/gin_utils.py", line 129, in run
    app.run(
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/keremturgutlu/t5x/t5x/train.py", line 789, in main
    _main(argv)
  File "/home/keremturgutlu/t5x/t5x/train.py", line 835, in _main
    train_using_gin()
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/keremturgutlu/t5x/t5x/train.py", line 528, in train
    _run_training_eval(first_run=True)
  File "/home/keremturgutlu/t5x/t5x/train.py", line 492, in _run_training_eval
    trainer.compile_eval({  # pytype: disable=wrong-arg-types  # jax-ndarray
  File "/home/keremturgutlu/t5x/t5x/trainer.py", line 611, in compile_eval
    self._compiled_eval_step_cache[cache_key] = self._partitioner.compile(
  File "/home/keremturgutlu/t5x/t5x/partitioning.py", line 805, in compile
    return partitioned_fn.lower(*args).compile()
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/jax/_src/stages.py", line 600, in compile
    self._lowering.compile(**kw),
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2816, in compile
    self._executable = UnloadedMeshExecutable.from_hlo(
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 3028, in from_hlo
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 526, in compile_or_get_cached
    return backend_compile(backend, serialized_computation, compile_options,
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/keremturgutlu/.local/lib/python3.8/site-packages/jax/_src/dispatch.py", line 471, in backend_compile
    return backend.compile(built_c, compile_options=options)
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: XLA:TPU compile permanent error. Ran out of memory in memory space hbm. Used 62.66G of 15.48G hbm. Exceeded hbm capacity by 47.18G.

Total hbm usage >= 63.18G:
    reserved        530.00M 
    program          62.66G 
    arguments            0B 

Output size 0B; shares 0B with arguments.

Program hbm requirement 62.66G:
    global            2.04M
    HLO temp         62.66G (100.0% utilization: Unpadded (62.59G) Padded (62.59G), 0.1% fragmentation (64.22M))

  Largest program allocations in hbm:

  1. Size: 62.59G
     Operator: op_name="pjit(<lambda>)/jit(main)/Transformer/Transformer.decode/decoder/logits_dense/dot_general[dimension_numbers=(((2,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/keremturgutlu/t5x/t5x/examples/scalable_t5/layers.py" source_line=449
     Shape: f32[128,512,256384]{2,1,0:T(8,128)}
     Unpadded size: 62.59G
     XLA label: fusion.288.remat = fusion(copy.290, fusion.347, get-tuple-element.720, convert.227, ...(+1)), kind=kOutput, calls=fused_computation.210.clone
     Allocation type: HLO temp
     ==========================

  2. Size: 1.00M
     Shape: s32[512,512]{1,0:T(8,128)}
     Unpadded size: 1.00M
     XLA label: constant literal
     Allocation type: global
     ==========================

  3. Size: 1.00M
     Shape: s32[512,512]{1,0:T(8,128)}
     Unpadded size: 1.00M
     XLA label: constant literal
     Allocation type: global
     ==========================

  4. Size: 256.0K
     Shape: s32[128,512]{0,1:T(8,128)}
     Unpadded size: 256.0K
     XLA label: copy.264 = copy(param.4), sharding={devices=[8,1]0,1,2,3,4,5,6,7}
     Allocation type: HLO temp
     ==========================

  5. Size: 256.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/Transformer/Transformer.decode/decoder/decoder_norm/rsqrt" source_file="/home/keremturgutlu/t5x/t5x/examples/scalable_t5/layers.py" source_line=717
     Shape: f32[128,512]{1,0:T(8,128)}
     Unpadded size: 256.0K
     XLA label: fusion.347 = fusion(fusion.309), kind=kLoop, calls=fused_computation.266
     Allocation type: HLO temp
     ==========================

  6. Size: 256.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/select_n" source_file="/home/keremturgutlu/t5x/t5x/losses.py" source_line=50
     Shape: f32[128,512]{1,0:T(8,128)}
     Unpadded size: 256.0K
     XLA label: copy.290 = copy(fusion.332)
     Allocation type: HLO temp
     ==========================

  7. Size: 256.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/add" source_file="/home/keremturgutlu/t5x/t5x/losses.py" source_line=50
     Shape: f32[128,512]{0,1:T(8,128)}
     Unpadded size: 256.0K
     XLA label: fusion.344 = fusion(copy.291, copy.288), kind=kLoop, calls=fused_computation.263
     Allocation type: HLO temp
     ==========================

  8. Size: 256.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/Transformer/Transformer.decode/decoder/logits_dense/dot_general[dimension_numbers=(((2,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/keremturgutlu/t5x/t5x/examples/scalable_t5/layers.py" source_line=449
     Shape: f32[128,512]{1,0:T(8,128)}
     Unpadded size: 256.0K
     XLA label: fusion.288.remat = fusion(copy.290, fusion.347, get-tuple-element.720, convert.227, ...(+1)), kind=kOutput, calls=fused_computation.210.clone
     Allocation type: HLO temp
     ==========================

  9. Size: 256.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/add" source_file="/home/keremturgutlu/t5x/t5x/losses.py" source_line=50
     Shape: f32[128,512]{1,0:T(8,128)}
     Unpadded size: 256.0K
     XLA label: copy.292 = copy(fusion.344)
     Allocation type: HLO temp
     ==========================

  10. Size: 4.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/reduce_sum[axes=(0, 1)]" source_file="/home/keremturgutlu/t5x/t5x/models.py" source_line=1394
     Shape: (s32[]{:T(256)}, pred[128,512]{0,1:T(8,128)(4,1)})
     Unpadded size: 4.0K
     XLA label: fusion.333 = fusion(copy.279), kind=kLoop, calls=fused_computation.252
     Allocation type: HLO temp
     ==========================

  11. Size: 4.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/Transformer/Transformer.decode/decoder/while/body/remat/decoder/encoder_decoder_attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/home/keremturgutlu/t5x/t5x/examples/scalable_t5/layers.py" source_line=166
     Shape: (bf16[128,6,512]{2,1,0:T(8,128)(2,1)}, bf16[128,6,512,512]{2,3,1,0:T(8,128)(2,1)})
     Unpadded size: 4.0K
     XLA label: fusion.474 = fusion(fusion.465, fusion.470, get-tuple-element.1410, get-tuple-element.1394, ...(+1)), kind=kOutput, calls=fused_computation.285.clone
     Allocation type: HLO temp
     ==========================

  12. Size: 4.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/Transformer/Transformer.decode/decoder/while/body/remat/decoder/self_attention/out/dot_general[dimension_numbers=(((2, 3), (0, 1)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/keremturgutlu/t5x/t5x/examples/scalable_t5/layers.py" source_line=449
     Shape: (f32[128,512]{1,0:T(8,128)}, bf16[128,512,512]{1,2,0:T(8,128)(2,1)})
     Unpadded size: 4.0K
     XLA label: fusion.464 = fusion(get-tuple-element.1369, get-tuple-element.1406, select.60, fusion.449, ...(+3)), kind=kOutput, calls=fused_computation.108.clone
     Allocation type: HLO temp
     ==========================

  13. Size: 4.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/Transformer/Transformer.decode/decoder/while/body/remat/decoder/self_attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/home/keremturgutlu/t5x/t5x/examples/scalable_t5/layers.py" source_line=166
     Shape: (bf16[128,6,512]{2,1,0:T(8,128)(2,1)}, bf16[128,6,512,512]{2,3,1,0:T(8,128)(2,1)})
     Unpadded size: 4.0K
     XLA label: fusion.460 = fusion(copy.346, fusion.453, fusion.456, fusion.445, ...(+4)), kind=kOutput, calls=fused_computation.284.clone
     Allocation type: HLO temp
     ==========================

  14. Size: 4.0K
     Shape: (f32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, f32[]{:T(256)}, f32[]{:T(256)}, /*index=5*/s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, /*index=10*/s32[]{:T(256)}, f32[]{:T(256)}, f32[]{:T(256)}, s32[]{:T(256)}, f32[]{:T(256)}, /*index=15*/s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, /*index=20*/s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, /*index=25*/s32[]{:T(256)}, f32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, f32[]{:T(256)}, /*index=30*/s32[]{:T(256)}, f32[]{:T(256)}, f32[]{:T(256)}, s32[]{:T(256)})
     Unpadded size: 4.0K
     XLA label: tuple.94 = tuple(get-tuple-element.1416, get-tuple-element.1417, constant.352, subtract.17, ...(+30))
     Allocation type: HLO temp
     ==========================

  15. Size: 4.0K
     Shape: (s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)}, /*index=5*/s32[]{:T(256)}, s32[]{:T(256)}, s32[]{:T(256)})
     Unpadded size: 4.0K
     XLA label: all-reduce.11 = all-reduce(get-tuple-element.1013, fusion.339, fusion.362, fusion.337, ...(+4)), channel_id=2, replica_groups={{0}}, to_apply=region_25.1034
     Allocation type: HLO temp
     ==========================

  16. Size: 4.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/Transformer/Transformer.decode/decoder/while/body/remat/decoder/encoder_decoder_attention/out/dot_general[dimension_numbers=(((2, 3), (0, 1)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/keremturgutlu/t5x/t5x/examples/scalable_t5/layers.py" source_line=449
     Shape: (f32[128,512]{1,0:T(8,128)}, bf16[128,512,512]{1,2,0:T(8,128)(2,1)})
     Unpadded size: 4.0K
     XLA label: fusion.480 = fusion(get-tuple-element.1232, get-tuple-element.1395, select.60, fusion.479), kind=kOutput, calls=fused_computation.110.clone
     Allocation type: HLO temp
     ==========================

  17. Size: 4.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/reduce_sum[axes=(0, 1)]" source_file="/home/keremturgutlu/t5x/t5x/models.py" source_line=1394
     Shape: (s32[]{:T(256)}, pred[128,512]{0,1:T(8,128)(4,1)})
     Unpadded size: 4.0K
     XLA label: fusion.335 = fusion(copy.271), kind=kLoop, calls=fused_computation.254
     Allocation type: HLO temp
     ==========================

  18. Size: 4.0K
     Shape: (f32[]{:T(256)}, f32[]{:T(256)}, f32[]{:T(256)})
     Unpadded size: 4.0K
     XLA label: all-reduce.12 = all-reduce(fusion.346, get-tuple-element.929, get-tuple-element.928), channel_id=1, replica_groups={{0}}, to_apply=region_24.1023
     Allocation type: HLO temp
     ==========================

  19. Size: 4.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/reduce_sum[axes=(0, 1)]" source_file="/home/keremturgutlu/t5x/t5x/losses.py" source_line=157
     Shape: (f32[]{:T(256)}, f32[]{:T(256)})
     Unpadded size: 4.0K
     XLA label: fusion.341 = fusion(copy.264, fusion.344, copy.293), kind=kLoop, calls=fused_computation.260
     Allocation type: HLO temp
     ==========================

  20. Size: 4.0K
     Operator: op_name="pjit(<lambda>)/jit(main)/Transformer/Transformer.decode/decoder/logits_dense/dot_general[dimension_numbers=(((2,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/home/keremturgutlu/t5x/t5x/examples/scalable_t5/layers.py" source_line=449
     Shape: (f32[128,512]{1,0:T(8,128)}, f32[128,512,256384]{2,1,0:T(8,128)})
     Unpadded size: 4.0K
     XLA label: fusion.288.remat = fusion(copy.290, fusion.347, get-tuple-element.720, convert.227, ...(+1)), kind=kOutput, calls=fused_computation.210.clone
     Allocation type: HLO temp
     ==========================
```

Appreciate any pointers to fix this issue, thanks!

**Comment by allegra-noto** [comment]
Having trouble training a umt5, getting an error that the task I created does not exist in any of the task cache directories. Can I see how you defined your task?
