### ISSUE TITLE
[Crash,regression] ImportError: cannot import name 'absl_flags' from 'fiddle' (/tmp/t5x/t5x/fiddle/__init__.py)

### ISSUE THREAD

**Issue by nouiz** [google-research/t5x#1256]
```commit cbc20f47009f6591fd96785f5d61e994aa47ed90
Author: Eugene Brevdo <ebrevdo@google.com>
Date:   Mon May 1 14:43:53 2023 -0700

    [Fiddle] Fix a bug in dag comparison of literals like integers and strings.
```
This commit introduced this error:
```
/# python ${T5X_DIR}/t5x/train.py \
>         --gin_file="${T5X_DIR}/t5x/contrib/gpu/scripts_gpu/dummy_wikipedia_config/small_pretrain_dummy_wikipedia.gin" \
>         --gin.MODEL_DIR=\"${OUTPUT_DIR}/model_dir\" \
>         --gin.network.T5Config.dtype=\"bfloat16\"  \
>         --gin.TRAIN_STEPS=100 \
>         --gin.CheckpointConfig.save=None \
>         --multiprocess_gpu
2023-05-02 16:53:16.868687: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/tmp/t5x/t5x/train.py", line 734, in <module>
    from t5x import config_utils
  File "/usr/local/lib/python3.10/dist-packages/t5x/config_utils.py", line 26, in <module>
    from fiddle import absl_flags as fdl_flags
ImportError: cannot import name 'absl_flags' from 'fiddle' (/tmp/t5x/t5x/fiddle/__init__.py)
```

The fiddle packages and the t5x.fiddle packages end up being mixed during the import.
If I revert to commit 776279bdacd8c5a2d3e8ce0f2e7064bd98e98b47, it works.

**Comment by sherhut** [comment]
@ebrevdo Could you take a look?

**Comment by ebrevdo** [comment]
What version of fiddle are you using?  The t5x setup.py now points to version 0.2.5

**Comment by ebrevdo** [comment]
I was able to reproduce.  Will send a fix.

**Comment by ebrevdo** [comment]
The problem is the train.py file sits in the t5x directory, and since `sys.path` the cwd when running, it will look there first for modules.  I'll probably rename the `fiddle` directory.

**Comment by nouiz** [comment]
Thanks for the quick fix.
