### ISSUE TITLE
t5x dependency is broken

### ISSUE THREAD

**Issue by nouiz** [google-research/t5x#1297]
JAX nightly CI on GPU is broken:

https://github.com/google/jax/actions/runs/5121223917

The error:
```
Traceback (most recent call last):
  File "/localdir/e2e_tests_workspace/t5x/t5x/train.py", line 40, in <module>
    from t5x import checkpoints
  File "/localdir/e2e_tests_workspace/t5x/t5x/__init__.py", line 17, in <module>
    import t5x.adafactor
  File "/localdir/e2e_tests_workspace/t5x/t5x/adafactor.py", line 64, in <module>
    from t5x import utils
  File "/localdir/e2e_tests_workspace/t5x/t5x/utils.py", line 45, in <module>
    from t5x import checkpoints
  File "/localdir/e2e_tests_workspace/t5x/t5x/checkpoints.py", line 55, in <module>
    from t5x import optimizers
  File "/localdir/e2e_tests_workspace/t5x/t5x/optimizers.py", line 38, in <module>
    from jestimator import amos
  File "/usr/local/lib/python3.8/dist-packages/jestimator/__init__.py", line 20, in <module>
    from . import amos_helper
  File "/usr/local/lib/python3.8/dist-packages/jestimator/amos_helper.py", line 24, in <module>
    from jax.experimental.pjit import PartitionSpec
ImportError: cannot import name 'PartitionSpec' from 'jax.experimental.pjit' (/usr/local/lib/python3.8/dist-packages/jax/experimental/pjit.py)
```

This need the dev version of jestimator. Can we fix update t5x dependency to ask for the dev version of jestimator?

**Comment by yhtang** [comment]
Related: #1294

**Comment by yhtang** [comment]
Filed [issue](https://github.com/google-research/jestimator/issues/30) in jestimator repo to request a new PyPI release.

**Comment by KEHANG** [comment]
It should be fixed by now (https://github.com/google-research/t5x/pull/1299)
