### ISSUE TITLE
DuplicateFlagError when first running the code

### ISSUE THREAD

**Issue by ChaosCodes** [google-research/t5x#236]
Hello, I am trying to run the code on my GPU server. However, after I installed the package, I got such an error.

This is the error msg, could you help me with this?

```shell
Traceback (most recent call last):
  File "/home/guangtao/t5x/t5x/train.py", line 617, in <module>
    gin_utils.run(main)
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/t5x/gin_utils.py", line 103, in run
    app.run(
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/guangtao/t5x/t5x/train.py", line 596, in main
    _main(argv)
  File "/home/guangtao/t5x/t5x/train.py", line 609, in _main
    gin_utils.parse_gin_flags(
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/t5x/gin_utils.py", line 50, in parse_gin_flags
    import t5.data  # pylint:disable=unused-import,g-import-not-at-top
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/t5/__init__.py", line 19, in <module>
    import t5.models
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/t5/models/__init__.py", line 17, in <module>
    import t5.models.mesh_transformer
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/t5/models/mesh_transformer.py", line 22, in <module>
    import mesh_tensorflow.transformer.dataset as transformer_dataset
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/mesh_tensorflow/transformer/__init__.py", line 29, in <module>
    import mesh_tensorflow.transformer.utils
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/mesh_tensorflow/transformer/utils.py", line 50, in <module>
    tf.flags.DEFINE_multi_string("gin_file", None, "Path to a Gin file.")
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/absl/flags/_defines.py", line 657, in DEFINE_multi_string
    return DEFINE_multi(
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/absl/flags/_defines.py", line 620, in DEFINE_multi
    return DEFINE_flag(
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/absl/flags/_defines.py", line 140, in DEFINE_flag
    fv[flag.name] = flag
  File "/home/guangtao/.conda/envs/prompt-tuning/lib/python3.10/site-packages/absl/flags/_flagvalues.py", line 439, in __setitem__
    raise _exceptions.DuplicateFlagError.from_flag(name, self)
absl.flags._exceptions.DuplicateFlagError: The flag 'gin_file' is defined twice. First from t5x/train.py, Second from mesh_tensorflow.transformer.utils.  Description from first occurrence: Path to gin configuration file. Multiple paths may be passed and will be imported in the given order, with later configurations  overriding earlier ones.;
    repeat this option to specify a list of values
```

**Comment by ChaosCodes** [comment]
Solved now.

**Comment by StephennFernandes** [comment]
@ChaosCodes hey were you able to run the code while all the GPUs are being used ? 
 
on my GPU server the model is running only on the 1st GPU
