### ISSUE TITLE
`[OS error: Too many open files]` when saving checkpoint of model with 48 encoder layers and 48 decoder layers

### ISSUE THREAD

**Issue by felixzli** [google-research/t5x#447]
Hello,
I tried to train a model with `num_encoder_layers = 48` and `num_decoder_layers = 48`. I got the following error:

```
I0424 03:25:54.615840 140410741775424 checkpoints.py:600] Saving checkpoint for step 5000 to /mnt/disks/persist/t5_training_models/final_exps/pretraining/LIME/t5_48_bs32/checkpoint_5000.tmp-1650770754
Traceback (most recent call last):
  File "./t5x/train.py", line 635, in <module>
    gin_utils.run(main)
  File "/mnt/disks/persist/felix-t5x/t5x/gin_utils.py", line 103, in run
    app.run(
  File "/mnt/disks/persist/envs/t5/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/mnt/disks/persist/envs/t5/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "./t5x/train.py", line 614, in main
    _main(argv)
  File "./t5x/train.py", line 632, in _main
    train_using_gin()
  File "/mnt/disks/persist/envs/t5/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/mnt/disks/persist/envs/t5/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/mnt/disks/persist/envs/t5/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "./t5x/train.py", line 519, in train
    checkpointer.save(trainer.train_state,
  File "/mnt/disks/persist/felix-t5x/t5x/checkpoints.py", line 607, in save
    written_state_dict = self._write_state_to_tensorstore(
  File "/mnt/disks/persist/felix-t5x/t5x/checkpoints.py", line 720, in _write_state_to_tensorstore
    written_state_dict = _run_future_tree(future_written_state)
  File "/mnt/disks/persist/felix-t5x/t5x/checkpoints.py", line 160, in _run_future_tree
    leaves = loop.run_until_complete(asyncio.gather(*future_leaves))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/mnt/disks/persist/felix-t5x/t5x/checkpoints.py", line 699, in _write_array
    await t[param_info.local_chunk_info.slice].write(arr)
ValueError: Error writing local file "/mnt/disks/persist/t5_training_models/final_exps/pretraining/LIME/t5_48_bs32/checkpoint_5000.tmp-1650770754/target.decoder.layers_36.encoder_decoder_attention.value.kernel/0.0": Failed to open lock file: /mnt/disks/persist/t5_training_models/final_exps/pretraining/LIME/t5_48_bs32/checkpoint_5000.tmp-1650770754/target.decoder.layers_36.encoder_decoder_attention.value.kernel/0.0.__lock [OS error: Too many open files]
  In call to configurable 'train' (<function train at 0x7fb1e5e8bca0>)
/mnt/disks/persist/t5_training_models/final_exps/pretraining/LIME/t5_48_bs32

```

Thanks for any help.

**Comment by adarob** [comment]
Can you try setting `ulimit -n 1200` or an even larger number?

**Comment by felixzli** [comment]
Thank you, this worked.
