### ISSUE TITLE
FAIL to run "Example: English to German translation" from README file

### ISSUE THREAD

**Issue by leiterenato** [google-research/t5x#617]
Compute environment:
 - Google Cloud TPU VM (base image)
 - 1 x TPU V3-8
 - Default installation, according to README file

Storage:
 - I tried both with local disks (from TPU VM) and on Google Cloud Storage

Running this example, as described in the README file, I got the following error:
```
...
I0620 18:55:27.067202 139969230261312 train.py:545] Epoch 0 of 100
I0620 18:55:27.067452 139952425035520 logging_writer.py:48] [0] collection=train timing/compilation_seconds=80.777680
I0620 18:55:27.068523 139969230261312 train.py:551] BEGIN Train loop.
I0620 18:55:27.069384 139969230261312 train.py:556] Training for 500 steps.
I0620 18:55:27.071459 139969230261312 trainer.py:487] Training: step 0
I0620 18:55:37.198480 139969230261312 trainer.py:487] Training: step 46
I0620 18:55:47.225553 139969230261312 trainer.py:487] Training: step 90
I0620 18:55:57.255041 139969230261312 trainer.py:487] Training: step 134
I0620 18:56:07.280249 139969230261312 trainer.py:487] Training: step 178
I0620 18:56:17.305412 139969230261312 trainer.py:487] Training: step 222
I0620 18:56:27.334421 139969230261312 trainer.py:487] Training: step 266
I0620 18:56:37.359880 139969230261312 trainer.py:487] Training: step 310
I0620 18:56:47.386486 139969230261312 trainer.py:487] Training: step 354
I0620 18:56:57.412878 139969230261312 trainer.py:487] Training: step 398
I0620 18:57:07.443236 139969230261312 trainer.py:487] Training: step 442
I0620 18:57:17.466779 139969230261312 trainer.py:487] Training: step 486
I0620 18:57:20.668031 139969230261312 train.py:581] END Train loop.
I0620 18:57:20.668265 139969230261312 train.py:454] Compiling training eval loop.
I0620 18:57:24.448034 139952425035520 logging_writer.py:48] [500] collection=train accuracy=0.213222, cross_ent_loss=143349.328000, cross_ent_loss_per_all_target_tokens=4.374674, learning_rate=0.010000, learning_rate/current=0.009999999776482582, loss=143754.976000, loss_per_all_target_tokens=4.387054, loss_per_nonpadding_target_token=5.047726, nonpadding_fraction=0.869115, timing/seconds=117.008831, timing/seqs=64000, timing/seqs_per_second=546.967261, timing/seqs_per_second_per_core=68.370908, timing/steps_per_second=4.273182, timing/target_tokens_per_second=140023.618929, timing/target_tokens_per_second_per_core=17502.952366, z_loss=405.720469, z_loss_per_all_target_tokens=0.012382
I0620 18:57:36.698853 139951174522624 logging_writer.py:48] [500] collection=training_eval/wmt_t2t_ende_v003 timing/compilation_seconds=15.152848
I0620 18:57:36.700013 139969230261312 train.py:459] Computing training evaluation metrics.
I0620 18:57:37.040851 139969230261312 trainer.py:529] Evaluating: wmt_t2t_ende_v003.
I0620 18:57:39.755579 139951174522624 logging_writer.py:48] [500] collection=training_eval/wmt_t2t_ende_v003 accuracy=0.298345, cross_ent_loss=119181.912500, cross_ent_loss_per_all_target_tokens=3.637143, loss=119662.062500, loss_per_all_target_tokens=3.651796, loss_per_nonpadding_target_token=4.061035, nonpadding_fraction=0.899228, timing/seconds=2.427278, timing/seqs=2560, timing/seqs_per_second=1054.679339, timing/seqs_per_second_per_core=131.834917, timing/steps_per_second=8.239682, timing/target_tokens_per_second=269997.910706, timing/target_tokens_per_second_per_core=33749.738838, z_loss=480.150391, z_loss_per_all_target_tokens=0.014653
I0620 18:57:39.886704 139969230261312 train.py:473] Running inference evaluation.
Traceback (most recent call last):
  File "/home/renatoleite/workspace/t5x/t5x/train.py", line 695, in <module>
    gin_utils.run(main)
  File "/home/renatoleite/workspace/t5x/t5x/gin_utils.py", line 107, in run
    app.run(
  File "/home/renatoleite/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/renatoleite/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/renatoleite/workspace/t5x/t5x/train.py", line 673, in main
    _main(argv)
  File "/home/renatoleite/workspace/t5x/t5x/train.py", line 693, in _main
    train_using_gin()
  File "/home/renatoleite/.local/lib/python3.8/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/renatoleite/.local/lib/python3.8/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/renatoleite/.local/lib/python3.8/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/renatoleite/workspace/t5x/t5x/train.py", line 616, in train
    _run_inference_eval()
  File "/home/renatoleite/workspace/t5x/t5x/train.py", line 475, in _run_inference_eval
    all_metrics, _, _ = evaluator.evaluate(
TypeError: evaluate() got an unexpected keyword argument 'predict_with_aux_fn'
  In call to configurable 'train' (<function train at 0x7f4b7ae3c8b0>)
```

I checked the .gin file and the variables seems to be set correctly.
Any idea what could be generating this error?

**Comment by leiterenato** [comment]
Hi @rjagerman
Thanks for the reply.
I manage to make this work by uninstalling the current version and installing `seqio-nightly`.
Closing this issue as this solved my problem.
Thank you again
