### ISSUE TITLE
Missing test coverage for T5X against SeqIO

### ISSUE THREAD

**Issue by levskaya** [google-research/t5x#851]
The PR #847 

should not have been able to pass tests, as it is broken when testing against current `seqio-nightly==0.0.11.dev20221020` with an error like:

```
Traceback (most recent call last):
  File "/t5x_home/t5x/train.py", line 763, in <module>
    gin_utils.run(main)
  File "/t5x_home/t5x/gin_utils.py", line 107, in run
    app.run(
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/t5x_home/t5x/train.py", line 727, in main
    _main(argv)
  File "/t5x_home/t5x/train.py", line 757, in _main
    train_using_gin()
  File "/usr/local/lib/python3.8/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.8/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.8/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/t5x_home/t5x/train.py", line 259, in train
    train_iter = get_dataset_fn(train_dataset_cfg, ds_shard_id, num_ds_shards,
  File "/t5x_home/t5x/utils.py", line 1411, in get_dataset
    return get_dataset_inner(cfg, shard_info, feature_converter_cls, seed,
  File "/t5x_home/t5x/utils.py", line 1433, in get_dataset_inner
    return seqio.get_dataset(
TypeError: get_dataset() got an unexpected keyword argument 'batch_size'
  In call to configurable 'train' (<function train at 0x7f0ac9d769d0>)
```

We've temporarily pinned t5x setup.py to install seqio at HEAD, but this indicates some missing test coverage - ideally the default install of t5x works with the seqio version it installs, whatever that is.

**Comment by adarob** [comment]
Installing SeqIO from head in #850
