### ISSUE TITLE
jax preallocate 90% of 32G memory but more allocation still happen

### ISSUE THREAD

**Issue by romanbrickie** [google-research/t5x#870]
![image](https://user-images.githubusercontent.com/3797521/197793040-a97fb21c-8645-4104-bf0a-94f63af64a65.png)

2022-10-25 21:52:08.138224: W external/org_tensorflow/tensorflow/tsl/framework/bfc_allocator.cc:479] Allocator (GPU_0_bfc) ran out of memory trying to allocate 27.93GiB (rounded to 29995136256)requested by op
2022-10-25 21:52:08.139090: W external/org_tensorflow/tensorflow/tsl/framework/bfc_allocator.cc:492] **__________________________________________________________________________________________________
2022-10-25 21:52:08.148530: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2153] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 29995136128 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  475.37MiB
              constant allocation:   512.0KiB
        maybe_live_out allocation:  474.37MiB
     preallocated temp allocation:   27.93GiB
  preallocated temp fragmentation:    34.0KiB (0.00%)
                 total allocation:   28.40GiB
              total fragmentation:   615.5KiB (0.00%)
Peak buffers:
        Buffer 1:
                Size: 1.96GiB
                Operator: op_name="pjit(train_step)/jit(main)/mul" source_file="/data/t5x/t5x/losses.py" source_line=139
                XLA Label: fusion
                Shape: f32[32768,16064]
                ==========================

        Buffer 2:
                Size: 1.96GiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.decode/decoder/logits_dense/dot_general[dimension_numbers=(((2,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=384
                XLA Label: custom-call
                Shape: f32[32768,16064]
                ==========================

        Buffer 3:
                Size: 1004.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.decode/decoder/token_embedder/convert_element_type[new_dtype=bfloat16 weak_type=False]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=498
                XLA Label: fusion
                Shape: bf16[16064,32768]
                ==========================

        Buffer 4:
                Size: 1004.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.decode/decoder/token_embedder/convert_element_type[new_dtype=bfloat16 weak_type=False]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=498
                XLA Label: fusion
                Shape: bf16[16064,32768]
                ==========================

        Buffer 5:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_5/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 6:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_4/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

        Buffer 7:
                Size: 96.00MiB
                XLA Label: fusion
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 8:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_4/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 9:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_3/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

        Buffer 10:
                Size: 96.00MiB
                XLA Label: fusion
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 11:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_3/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 12:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_2/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

        Buffer 13:
                Size: 96.00MiB
                XLA Label: fusion
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 14:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_2/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 15:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_1/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

2022-10-25 21:52:08.219469: W external/org_tensorflow/tensorflow/tsl/framework/bfc_allocator.cc:479] Allocator (GPU_1_bfc) ran out of memory trying to allocate 27.93GiB (rounded to 29995136256)requested by op
2022-10-25 21:52:08.220328: W external/org_tensorflow/tensorflow/tsl/framework/bfc_allocator.cc:492] **__________________________________________________________________________________________________
2022-10-25 21:52:08.231191: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2153] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 29995136128 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  475.37MiB
              constant allocation:   512.0KiB
        maybe_live_out allocation:  474.37MiB
     preallocated temp allocation:   27.93GiB
  preallocated temp fragmentation:    34.0KiB (0.00%)
                 total allocation:   28.40GiB
              total fragmentation:   615.5KiB (0.00%)
Peak buffers:
        Buffer 1:
                Size: 1.96GiB
                Operator: op_name="pjit(train_step)/jit(main)/mul" source_file="/data/t5x/t5x/losses.py" source_line=139
                XLA Label: fusion
                Shape: f32[32768,16064]
                ==========================

        Buffer 2:
                Size: 1.96GiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.decode/decoder/logits_dense/dot_general[dimension_numbers=(((2,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=384
                XLA Label: custom-call
                Shape: f32[32768,16064]
                ==========================

        Buffer 3:
                Size: 1004.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.decode/decoder/token_embedder/convert_element_type[new_dtype=bfloat16 weak_type=False]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=498
                XLA Label: fusion
                Shape: bf16[16064,32768]
                ==========================

        Buffer 4:
                Size: 1004.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.decode/decoder/token_embedder/convert_element_type[new_dtype=bfloat16 weak_type=False]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=498
                XLA Label: fusion
                Shape: bf16[16064,32768]
                ==========================

        Buffer 5:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_5/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 6:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_4/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

        Buffer 7:
                Size: 96.00MiB
                XLA Label: fusion
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 8:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_4/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 9:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_3/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

        Buffer 10:
                Size: 96.00MiB
                XLA Label: fusion
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 11:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_3/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 12:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_2/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

        Buffer 13:
                Size: 96.00MiB
                XLA Label: fusion
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 14:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_2/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 15:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_1/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

Traceback (most recent call last):
  File "/data/t5x/t5x/train.py", line 757, in <module>
    gin_utils.run(main)
  File "/data/t5x/t5x/gin_utils.py", line 107, in run
    app.run(
  File "/usr/local/lib/python3.9/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.9/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/data/t5x/t5x/train.py", line 717, in main
    _main(argv)
  File "/data/t5x/t5x/train.py", line 753, in _main
    train_using_gin()
  File "/usr/local/lib/python3.9/dist-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/usr/local/lib/python3.9/dist-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/usr/local/lib/python3.9/dist-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/t5x/t5x/train.py", line 601, in train
    train_summary = trainer.train(
  File "/data/t5x/t5x/trainer.py", line 502, in train
    train_state, metrics_update = train_step_fn(train_state, batch)
  File "/usr/local/lib/python3.9/dist-packages/jax/_src/stages.py", line 433, in __call__
    out_flat = self._executable.call(*args_flat)
  File "/usr/local/lib/python3.9/dist-packages/jax/interpreters/pxla.py", line 3408, in call
    return self.unsafe_call(*args)
  File "/usr/local/lib/python3.9/dist-packages/jax/_src/profiler.py", line 313, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/jax/interpreters/pxla.py", line 2068, in __call__
    out_bufs = self.xla_executable.execute_sharded_on_local_devices(
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 29995136128 bytes.
BufferAssignment OOM Debugging.
BufferAssignment stats:
             parameter allocation:  475.37MiB
              constant allocation:   512.0KiB
        maybe_live_out allocation:  474.37MiB
     preallocated temp allocation:   27.93GiB
  preallocated temp fragmentation:    34.0KiB (0.00%)
                 total allocation:   28.40GiB
              total fragmentation:   615.5KiB (0.00%)
Peak buffers:
        Buffer 1:
                Size: 1.96GiB
                Operator: op_name="pjit(train_step)/jit(main)/mul" source_file="/data/t5x/t5x/losses.py" source_line=139
                XLA Label: fusion
                Shape: f32[32768,16064]
                ==========================

        Buffer 2:
                Size: 1.96GiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.decode/decoder/logits_dense/dot_general[dimension_numbers=(((2,), (0,)), ((), ())) precision=None preferred_element_type=None]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=384
                XLA Label: custom-call
                Shape: f32[32768,16064]
                ==========================

        Buffer 3:
                Size: 1004.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.decode/decoder/token_embedder/convert_element_type[new_dtype=bfloat16 weak_type=False]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=498
                XLA Label: fusion
                Shape: bf16[16064,32768]
                ==========================

        Buffer 4:
                Size: 1004.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.decode/decoder/token_embedder/convert_element_type[new_dtype=bfloat16 weak_type=False]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=498
                XLA Label: fusion
                Shape: bf16[16064,32768]
                ==========================

        Buffer 5:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_5/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 6:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_4/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

        Buffer 7:
                Size: 96.00MiB
                XLA Label: fusion
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 8:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_4/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 9:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_3/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

        Buffer 10:
                Size: 96.00MiB
                XLA Label: fusion
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 11:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_3/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 12:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_2/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

        Buffer 13:
                Size: 96.00MiB
                XLA Label: fusion
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 14:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_2/attention/bqhd,bkhd->bhqk/jit(_einsum)/dot_general[dimension_numbers=(((3,), (3,)), ((0, 2), (0, 2))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.9/contextlib.py" source_line=79
                XLA Label: custom-call
                Shape: bf16[128,6,256,256]
                ==========================

        Buffer 15:
                Size: 96.00MiB
                Operator: op_name="pjit(train_step)/jit(main)/jvp(Transformer)/Transformer.encode/encoder/layers_1/pre_mlp_layer_norm/reduce_sum[axes=(2,)]" source_file="/data/t5x/t5x/examples/t5/layers.py" source_line=652
                XLA Label: fusion
                Shape: f32[128,256,768]
                ==========================

: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).
  In call to configurable 'train' (<function train at 0x7f0301798b80>)

**Comment by romanbrickie** [comment]
From watch info of nvidia-smi, I could see the preallocated memory size is around 29379. But from the number we could see that before OOM, 29549 bytes are allocated and ater that, jax still keep allocating.

**Comment by Qazalbash** [comment]
@romanbrickie are you able to solve this problem?
